// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr9aop-YL8sqp003tqlyYScV5BSeL0Jvw',
    appId: '1:897993564379:web:d8c96267bc527a22e26cfe',
    messagingSenderId: '897993564379',
    projectId: 'masar-app-f9283',
    authDomain: 'masar-app-f9283.firebaseapp.com',
    storageBucket: 'masar-app-f9283.firebasestorage.app',
    measurementId: 'G-ZF6D45BYHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDETFJrKjHXUFkELhZD1mcQclr2WLctCto',
    appId: '1:897993564379:android:c47c80c78ce72ed4e26cfe',
    messagingSenderId: '897993564379',
    projectId: 'masar-app-f9283',
    storageBucket: 'masar-app-f9283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYclhrpWlxxcfiZHVPgP9s5B0hIIMXA-4',
    appId: '1:897993564379:ios:6daaa2cf94540b95e26cfe',
    messagingSenderId: '897993564379',
    projectId: 'masar-app-f9283',
    storageBucket: 'masar-app-f9283.firebasestorage.app',
    iosBundleId: 'com.example.etla3YaOsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYclhrpWlxxcfiZHVPgP9s5B0hIIMXA-4',
    appId: '1:897993564379:ios:6daaa2cf94540b95e26cfe',
    messagingSenderId: '897993564379',
    projectId: 'masar-app-f9283',
    storageBucket: 'masar-app-f9283.firebasestorage.app',
    iosBundleId: 'com.example.etla3YaOsta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr9aop-YL8sqp003tqlyYScV5BSeL0Jvw',
    appId: '1:897993564379:web:eeee897057a54504e26cfe',
    messagingSenderId: '897993564379',
    projectId: 'masar-app-f9283',
    authDomain: 'masar-app-f9283.firebaseapp.com',
    storageBucket: 'masar-app-f9283.firebasestorage.app',
    measurementId: 'G-0L9JZ2VSLD',
  );
}
